# Generated by Django 5.0.7 on 2024-07-17 19:39

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_todoitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=my_app.models.todo_upload_path),
        ),
    ]
